### PR TITLE
Bump to version 0.2.0

### PR DESCRIPTION
**Pull request by ruspl-afed**
Bundle ru.arsysop.mola.runtime

Signed-off-by: Alexander Fedorov <alexander.fedorov@arsysop.ru>

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#8](https://github.com/arsysop/mola/issues/8) is now in scope, role is `REV`

**Review by eparovyshnaya — APPROVED** [review]

**Comment by 0crat** [comment]
Job `gh:arsysop/mola#8` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#8](https://github.com/arsysop/mola/issues/8) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @ruspl-afed[/z](https://www.0crat.com/u/ruspl-afed)

**Pull request merged**
