### PR TITLE
Switch target to 2019-12

### PR DESCRIPTION
**Pull request by ruspl-afed**
Signed-off-by: Alexander Fedorov <alexander.fedorov@arsysop.ru>

### CODE REVIEW

**Comment by 0crat** [comment]
@ruspl-afed[/z](https://www.0crat.com/u/ruspl-afed) this pull request is too small, just 8 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @ruspl-afed[/z](https://www.0crat.com/u/ruspl-afed) please review this and merge or reject

**Review by eparovyshnaya — APPROVED** [review]
Looks workable

**Comment by 0crat** [comment]
Job `gh:arsysop/mola#9` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
