### PR TITLE
Configure maven build trriger on Push and on  PR

### PR DESCRIPTION
**Pull request by eparovyshnaya**

### CODE REVIEW

**Comment by 0crat** [comment]
@ruspl-afed[/z](https://www.0crat.com/u/ruspl-afed) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#7](https://github.com/arsysop/mola/issues/7) is now in scope, role is `REV`

**Review by ruspl-afed — APPROVED** [review]

**Comment by 0crat** [comment]
@ruspl-afed[/z](https://www.0crat.com/u/ruspl-afed) everybody who has role `REV` is banned at [#7](https://github.com/arsysop/mola/issues/7); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment]
Job `gh:arsysop/mola#7` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#7](https://github.com/arsysop/mola/issues/7) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @ruspl-afed[/z](https://www.0crat.com/u/ruspl-afed)

**Pull request merged**
